version: '3.9'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-container-chatbot
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODEL:-llama3.1}
    restart: unless-stopped

  chatbot:
    build: .
    container_name: langgraph-chatbot-container
    ports:
      - '8501:8501'
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

volumes:
  ollama_data: